// ── Creator data ──────────────────────────────────────────────────────────────
export const CREATORS = {
  finance: [
    {name:"Shivam Malik",handle:"@shivammalik09",yt:"—",ig:"—",platforms:["YT","IG"],color:"#00C48C",desc:"Personal finance educator making money simple for young Indians. Known for punchy, relatable Reels on budgeting, savings and avoiding bad debt.",tags:["Personal Finance","Budgeting","Savings"],rank:1},
    {name:"Abhishek Kar",handle:"@abhishekkarofficial",yt:"—",ig:"—",platforms:["YT","IG"],color:"#00C48C",desc:"Finance storyteller and author of 'The 1% Formula'. Covers wealth psychology, compounding habits and the mindset behind building long-term financial health in India.",tags:["Wealth Mindset","Compounding","Books"],rank:2},
    {name:"Sarthak Ahuja",handle:"@casarthakahuja",yt:"—",ig:"—",platforms:["IG"],color:"#00C48C",desc:"Chartered Accountant turning complex tax and finance concepts into crisp, actionable content. Covers income tax filing, GST, and CA career guidance for Indian professionals.",tags:["Taxation","GST","CA Career"],rank:3},
    {name:"Sharan Hegde",handle:"@financewithsharan",yt:"—",ig:"—",platforms:["YT","IG"],color:"#00C48C",desc:"India's most entertaining finance creator. GQ Most Influential Indian 2024. Covers insurance myths, SIPs, tax-saving, and debunks financial misinformation through viral Reels.",tags:["SIPs","Insurance","Financial Myths"],rank:4},
    {name:"Neha Nagar",handle:"@iamnehanagar",yt:"—",ig:"—",platforms:["IG"],color:"#00C48C",desc:"Finance influencer and international speaker covering personal finance, credit card hacks and side income strategies in Hindi for first-generation investors across India.",tags:["Hindi Finance","Credit Cards","Side Income"],rank:5},
    {name:"AISM India",handle:"@aismindia",yt:"—",ig:"—",platforms:["IG"],color:"#00C48C",desc:"Academy for Investment and Stock Market — educating retail investors on stock analysis, mutual funds, options trading, and building a passive income portfolio from scratch.",tags:["Stock Market","Options Trading","Passive Income"],rank:6},
    {name:"Sakchi Jain",handle:"@ca.sakchijain",yt:"—",ig:"—",platforms:["IG"],color:"#00C48C",desc:"Chartered Accountant creating sharp finance content on tax planning, income declaration, NRI taxation and everyday money decisions that salaried Indians face.",tags:["Tax Planning","NRI Finance","Salaried Finance"],rank:7},
    {name:"Groww.in",handle:"@groww_official",yt:"—",ig:"—",platforms:["IG"],color:"#00C48C",desc:"Official Instagram of Groww — India's leading investment platform. Shares market updates, mutual fund explainers, SIP guides and beginner investing tips for a 50M+ user base.",tags:["Mutual Funds","Investing Platform","Market Updates"],rank:8},
    {name:"Ankur Warikoo",handle:"@ankurwarikoo",yt:"—",ig:"—",platforms:["YT","IG"],color:"#00C48C",desc:"Entrepreneur, bestselling author of 'Make Epic Money'. Creates data-backed, youth-targeted content on personal finance, salary negotiation, budgeting and building financial independence early.",tags:["Personal Finance","Entrepreneurship","Money Books"],rank:9},
    {name:"Businessman Hindi Mindset",handle:"@businessman_hindi_mindset",yt:"—",ig:"—",platforms:["IG"],color:"#00C48C",desc:"Hindi-language business and finance channel breaking down entrepreneurship, investment philosophy and mindset strategies for India's Tier-2 and Tier-3 city audiences.",tags:["Hindi Business","Entrepreneurship","Tier-2 India"],rank:10},
  ],
  tech: [
    {name:"Gaurav Chaudhary (PhoneBuff)",handle:"@technicalguruji",yt:"—",ig:"—",platforms:["YT","IG"],color:"#2E6BFF",desc:"Technical Guruji — India's most-subscribed tech YouTuber with 23M+ subscribers. Makes technology simple in Hindi covering smartphone reviews, AI tools and gadget deep-dives.",tags:["Smartphones","Hindi Tech","AI Tools"],rank:1},
    {name:"Shlok Srivastava",handle:"@techburner",yt:"—",ig:"—",platforms:["YT","IG"],color:"#2E6BFF",desc:"Tech Burner — blends humour with in-depth tech reviews. CNN-News18 Indian of the Year 2025. Known for making tech fun for younger audiences and launching his own consumer brand OWN.",tags:["Tech Reviews","Humour","Youth Tech"],rank:2},
    {name:"Jai Arora",handle:"@tech_iela",yt:"—",ig:"—",platforms:["YT","IG"],color:"#2E6BFF",desc:"Tech creator covering budget smartphone reviews, accessory deep-dives and practical tech tips for Indian consumers who want the best value-for-money gadgets.",tags:["Budget Tech","Smartphones","Accessories"],rank:3},
    {name:"Naman Deshmukh",handle:"@techplusgadgets",yt:"—",ig:"—",platforms:["YT","IG"],color:"#2E6BFF",desc:"Gadget reviewer and tech educator covering smartphones, laptops, smartwatches and emerging tech trends. Known for hands-on comparisons and honest buying guides for Indian audiences.",tags:["Gadgets","Laptops","Buying Guides"],rank:4},
    {name:"Manoj Saru",handle:"@manajsaru",yt:"—",ig:"—",platforms:["YT","IG"],color:"#2E6BFF",desc:"Creator behind Technology Gyan — one of India's largest Hindi tech channels. Covers smartphone reviews, TV comparisons, Android tips and smart home guides for regional audiences.",tags:["Hindi Tech","TVs","Android Tips"],rank:5},
  ],
  fashion: [
    {name:"Nagma Mirajkar",handle:"@nagmamirajkar",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF3D71",desc:"Actor-turned-content creator and one of Instagram India's most-followed fashion voices. Known for vibrant styling, affordable fashion hauls, beauty routines and energetic Reels.",tags:["Fashion Hauls","Beauty","Lifestyle"],rank:1},
    {name:"Karron S Dhinggra",handle:"@theformaledit",yt:"—",ig:"—",platforms:["IG"],color:"#FF3D71",desc:"India's leading men's fashion creator. Covers formal wear, office styling, grooming routines and everyday fashion for the modern Indian professional man.",tags:["Men's Fashion","Formal Wear","Grooming"],rank:2},
    {name:"Komal Pandey",handle:"@komalpandey",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF3D71",desc:"Fashion filmmaker and stylist known for editorial-quality fashion storytelling. Covers high-fashion looks, sustainable styling, body positivity and creative Reels that push Indian fashion forward.",tags:["Fashion Films","Editorial","Sustainability"],rank:3},
    {name:"Kritika Khurana",handle:"@thatbohogirl",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF3D71",desc:"That Boho Girl — one of India's original fashion bloggers turned creator. Covers bohemian aesthetics, travel fashion, beauty and building a personal style identity.",tags:["Boho Fashion","Travel Style","Beauty"],rank:4},
    {name:"Ritik Mahajan",handle:"@ritikmahajan",yt:"—",ig:"—",platforms:["IG"],color:"#FF3D71",desc:"Men's lifestyle and fashion creator covering outfit ideas, grooming hacks, fitness aesthetics and the modern Indian man's wardrobe for Gen-Z and millennial audiences.",tags:["Men's Lifestyle","Grooming","Gen-Z Fashion"],rank:5},
    {name:"Sakshi Shrivas",handle:"@sakshishrivas",yt:"—",ig:"—",platforms:["IG"],color:"#FF3D71",desc:"Fashion and lifestyle creator known for accessible, everyday styling content. Covers outfit ideas, thrift and budget fashion, beauty hacks and relatable Indian girl content.",tags:["Everyday Fashion","Budget Style","Beauty"],rank:6},
    {name:"Masoom Minawala",handle:"@masoomminawala",yt:"—",ig:"—",platforms:["IG"],color:"#FF3D71",desc:"India's first fashion creator to attend Paris Fashion Week. Covers luxury fashion, international trends, brand collaborations and represents Indian fashion on global stages.",tags:["Luxury Fashion","Paris Fashion Week","Global Style"],rank:7},
    {name:"Sakshi Sindwani",handle:"@sakshisindwani",yt:"—",ig:"—",platforms:["IG"],color:"#FF3D71",desc:"Plus-size fashion creator and body positivity advocate. Known for celebrating all body types with bold, confident styling, affordable outfit ideas and empowering content for every size.",tags:["Plus-Size Fashion","Body Positivity","Inclusive Style"],rank:8},
  ],
  food: [
    {name:"Pooja Dhingra",handle:"@poojadhingra",yt:"—",ig:"—",platforms:["IG"],color:"#FF8A00",desc:"India's first macaron maker and pastry chef-entrepreneur. Founder of Le15 Patisserie. Covers French patisserie techniques, dessert recipes, baking tips and building a food business in India.",tags:["Patisserie","Baking","Food Business"],rank:1},
    {name:"Vikas Khanna",handle:"@vikaskhannagroup",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF8A00",desc:"Michelin-starred chef, filmmaker and humanitarian. Covers Indian heritage cuisine, restaurant culture, global culinary experiences and the stories behind traditional Indian recipes.",tags:["Michelin Star","Heritage Cuisine","Global Food"],rank:2},
    {name:"Shipra Khanna",handle:"@masterchefshiprakhanna",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF8A00",desc:"MasterChef India Season 2 winner. Covers restaurant-quality recipes made simple at home, festive cooking, health-conscious Indian meals and culinary travel across India.",tags:["MasterChef","Indian Recipes","Festive Food"],rank:3},
    {name:"Ranveer Brar",handle:"@ranveer.brar",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF8A00",desc:"Celebrity chef, MasterChef India judge and food philosopher. Known for deep culinary storytelling, traditional Indian recipes, ingredient history and making cooking feel like an art form.",tags:["MasterChef Judge","Traditional Recipes","Culinary Stories"],rank:4},
    {name:"Kunal Kapur",handle:"@chefkunal",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF8A00",desc:"Celebrity chef and TV host. Covers simple yet impressive Indian and international recipes, cooking techniques, kitchen tips and food culture for home cooks across India.",tags:["Celebrity Chef","Home Cooking","Food Culture"],rank:5},
    {name:"Hebbar's Kitchen",handle:"@hebbarskitchen",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF8A00",desc:"India's most trusted vegetarian recipe channel. Covers South Indian, North Indian and fusion recipes with step-by-step visual guides. Trusted by millions of home cooks daily.",tags:["Vegetarian","South Indian","Recipe Guides"],rank:6},
    {name:"Shivesh Bhatia",handle:"@shivesh17",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF8A00",desc:"Baking author and content creator known for stunning dessert photography and accessible baking recipes. Covers cakes, cookies, brownies and no-bake desserts for Indian home bakers.",tags:["Baking","Desserts","Food Photography"],rank:7},
    {name:"Eshaan Nagpal (Indian Bawarchi)",handle:"@indian_bawarchi",yt:"—",ig:"—",platforms:["IG"],color:"#FF8A00",desc:"Street food explorer and recipe creator celebrating India's regional food culture. Covers dhabha-style recipes, street food recreations and the lesser-known culinary gems of Indian cuisine.",tags:["Street Food","Regional Indian","Dhabha Recipes"],rank:8},
    {name:"Pankaj Bhadouria",handle:"@masterchefpankajbhadouria",yt:"—",ig:"—",platforms:["YT","IG"],color:"#FF8A00",desc:"MasterChef India Season 1 winner. Runs the Pankaj Bhadouria Culinary Academy. Covers homestyle Indian recipes, cooking school tips, healthy swaps and budget meal ideas.",tags:["MasterChef","Cooking Academy","Homestyle Recipes"],rank:9},
    {name:"Amar Sirohi (Foodie Incarnate)",handle:"@foodie_incarnate",yt:"—",ig:"—",platforms:["IG"],color:"#FF8A00",desc:"Food reviewer and restaurant critic exploring India's culinary landscape. Covers restaurant reviews, food trails, hidden gem eateries and the stories behind India's most beloved food spots.",tags:["Food Reviews","Restaurant Critic","Food Trails"],rank:10},
  ],
  gaming: [
    {name:"Techno Gamerz (Ujjwal Chaurasia)",handle:"@technogamerz",yt:"—",ig:"—",platforms:["YT","IG"],color:"#A855F7",desc:"India's biggest gaming YouTuber with 40M+ subscribers. Known for GTA 5 and Minecraft gameplay, entertaining commentary and being a trailblazer for India's gaming creator ecosystem.",tags:["GTA 5","Minecraft","Gaming Commentary"],rank:1},
    {name:"Total Gaming (Ajay)",handle:"@totalgaming_official",yt:"—",ig:"—",platforms:["YT","IG"],color:"#A855F7",desc:"One of India's top Free Fire and BGMI content creators. Known for high-energy gameplay, Pro tips and building a massive Hindi-speaking gaming community from Surat.",tags:["Free Fire","BGMI","Hindi Gaming"],rank:2},
    {name:"Dynamo Gaming (Aadi Sawant)",handle:"@dynamo__gaming",yt:"—",ig:"—",platforms:["YT","IG"],color:"#A855F7",desc:"Pioneer of PUBG Mobile content in India. Known for aggressive gameplay, clutch moments and mentoring the next generation of Indian esports talent through community tournaments.",tags:["PUBG Mobile","Esports","Gaming Community"],rank:3},
    {name:"Mortal (Naman Mathur)",handle:"@ig_mortal",yt:"—",ig:"—",platforms:["YT","IG"],color:"#A855F7",desc:"One of India's most respected esports players and content creators. Former S8UL co-founder. Covers BGMI, gaming commentary, lifestyle and Indian esports industry insights.",tags:["BGMI","Esports","S8UL"],rank:4},
    {name:"As Gaming (Sahil Rana)",handle:"@asgaming",yt:"—",ig:"—",platforms:["IG"],color:"#A855F7",desc:"Free Fire content creator and esports personality covering competitive gameplay, creator vlogs and gaming culture for India's mobile-first gaming audience.",tags:["Free Fire","Mobile Gaming","Esports"],rank:5},
    {name:"GamerFleet (Anshu Bisht)",handle:"@gamerfleet",yt:"—",ig:"—",platforms:["YT","IG"],color:"#A855F7",desc:"Popular Minecraft and GTA creator known for roleplay servers, gaming challenges and entertaining collaborative content with India's top gaming creators.",tags:["Minecraft","GTA RP","Gaming Collab"],rank:6},
    {name:"Kronten Gaming (Chetan Chandgude)",handle:"@krontengaming",yt:"—",ig:"—",platforms:["IG"],color:"#A855F7",desc:"BGMI and gaming lifestyle creator. Known for high-skill competitive content, team gameplay with leading Indian esports squads and behind-the-scenes gaming life vlogs.",tags:["BGMI","Competitive Gaming","Gaming Vlogs"],rank:7},
    {name:"Desi Gamers (Amit Sharma)",handle:"@desigamers",yt:"—",ig:"—",platforms:["YT","IG"],color:"#A855F7",desc:"Free Fire and reaction content creator. One of the most energetic gaming personalities in India with a loyal community built around fun, accessibility and regional gaming culture.",tags:["Free Fire","Reaction Content","Regional Gaming"],rank:8},
    {name:"Two Side Gamers",handle:"@twosidegamers",yt:"—",ig:"—",platforms:["IG"],color:"#A855F7",desc:"Duo gaming channel covering Free Fire, BGMI and gaming challenges. Known for fun collaborative format, couple gaming dynamic and high-energy content that resonates with young Indian audiences.",tags:["Duo Gaming","Free Fire","Gaming Challenges"],rank:9},
  ],
  fitness: [
    {name:"Simran Chopra",handle:"@simrun.chopra",yt:"—",ig:"—",platforms:["YT","IG"],color:"#00BBD6",desc:"India's leading nutrition and running coach. Covers mindful eating, marathon training, body recomposition and sustainable fitness habits — with a science-backed, no-fad approach.",tags:["Nutrition","Running","Mindful Eating"],rank:1},
    {name:"Pooja Makhija",handle:"@poojamakhija",yt:"—",ig:"—",platforms:["IG"],color:"#00BBD6",desc:"Celebrity nutritionist and author. Has worked with Bollywood stars. Covers evidence-based nutrition, Indian diet tips, gut health and making healthy eating practical for Indian families.",tags:["Celebrity Nutrition","Gut Health","Indian Diet"],rank:2},
    {name:"Namrata Purohit",handle:"@namratapurohit",yt:"—",ig:"—",platforms:["YT","IG"],color:"#00BBD6",desc:"India's leading Pilates instructor. Youngest globally certified Peak Pilates instructor. Covers Pilates for all levels, pre/post-natal fitness and mind-body wellness.",tags:["Pilates","Pre-Natal Fitness","Mind-Body Wellness"],rank:3},
    {name:"Luke Coutinho",handle:"@lukecoutinho",yt:"—",ig:"—",platforms:["IG"],color:"#00BBD6",desc:"Integrative lifestyle specialist covering holistic health — cancer support, intermittent fasting, sleep quality and treating root causes rather than symptoms through lifestyle medicine.",tags:["Holistic Health","Intermittent Fasting","Lifestyle Medicine"],rank:4},
    {name:"Rohit Khatri",handle:"@rohitkhatri",yt:"—",ig:"—",platforms:["YT","IG"],color:"#00BBD6",desc:"India's most-followed male fitness trainer on social media. Covers weight training, fat loss, supplement guidance and no-nonsense gym advice for Indian men building their fitness journey.",tags:["Weight Training","Fat Loss","Gym Advice"],rank:5},
    {name:"Varun Verma",handle:"@varunverma",yt:"—",ig:"—",platforms:["IG"],color:"#00BBD6",desc:"Fitness creator and online coach covering functional fitness, calisthenics, body transformation and helping everyday Indians build sustainable workout habits without expensive gym memberships.",tags:["Functional Fitness","Calisthenics","Transformations"],rank:6},
    {name:"Yasmin Karachiwala",handle:"@yasminkarachiwala",yt:"—",ig:"—",platforms:["YT","IG"],color:"#00BBD6",desc:"Celebrity fitness trainer and India's most sought-after Pilates expert. Has trained Katrina Kaif and Deepika Padukone. Covers Pilates, strength training and balanced fitness for women.",tags:["Celebrity Fitness","Pilates","Women's Fitness"],rank:7},
    {name:"Nitesh Soni",handle:"@niteshsoniy",yt:"—",ig:"—",platforms:["IG"],color:"#00BBD6",desc:"Fitness educator and natural bodybuilder covering gym training, nutrition science, supplement myths and building a strong physique through discipline and smart programming.",tags:["Bodybuilding","Nutrition Science","Natural Fitness"],rank:8},
    {name:"Soniya Singh Khatri",handle:"@fitgirl_08",yt:"—",ig:"—",platforms:["IG"],color:"#00BBD6",desc:"Female fitness creator covering fat loss, strength training for women, diet plans and motivating everyday Indian women to start and sustain their fitness journey.",tags:["Women's Fitness","Fat Loss","Strength Training"],rank:9},
  ],
};

// ── YouTube handles for live API fetching ──────────────────────────────────────
export const YT_HANDLE = {
  "Shivam Malik":"shivammalik09",
  "Abhishek Kar":"abhishekkar",
  "Sharan Hegde":"financewithsharan",
  "Ankur Warikoo":"warikoo",
  "Gaurav Chaudhary (PhoneBuff)":"TechnicalGuruji",
  "Shlok Srivastava":"TechBurner",
  "Jai Arora":"techielaofficial",
  "Naman Deshmukh":"TechPlusGadgetsyt",
  "Manoj Saru":"TechnologyGyan",
  "Nagma Mirajkar":"nagmamirajkar",
  "Komal Pandey":"komalpandey",
  "Kritika Khurana":"thatbohogirl",
  "Sakshi Sindwani":"sakshisindwani",
  "Masoom Minawala":"masoomminawala",
  "Vikas Khanna":"vikaskhannagroup",
  "Shipra Khanna":"MasterChefShipraKhanna",
  "Ranveer Brar":"RanveerBrar",
  "Kunal Kapur":"ChefKunalKapur",
  "Hebbar's Kitchen":"hebbars.kitchen",
  "Shivesh Bhatia":"shivesh17",
  "Pankaj Bhadouria":"PankajBhadouria",
  "Techno Gamerz (Ujjwal Chaurasia)":"technogamerz",
  "Total Gaming (Ajay)":"TotalGamingYT",
  "Dynamo Gaming (Aadi Sawant)":"DynamoGaming",
  "Mortal (Naman Mathur)":"MortaL",
  "GamerFleet (Anshu Bisht)":"GamerFleet",
  "Desi Gamers (Amit Sharma)":"DesiGamersYT",
  "Simran Chopra":"simrunchopra",
  "Namrata Purohit":"NamrataPurohit",
  "Rohit Khatri":"rohitkhatri",
  "Yasmin Karachiwala":"YasminKarachiwala",
};

// ── Verified YouTube URLs ──────────────────────────────────────────────────────
export const YT_VERIFIED = {
  "Shivam Malik":           "https://www.youtube.com/@shivammalik09",
  "Abhishek Kar":           "https://www.youtube.com/@abhishekkar",
  "Sharan Hegde":           "https://www.youtube.com/@financewithsharan",
  "Ankur Warikoo":          "https://www.youtube.com/@warikoo",
  "Gaurav Chaudhary (PhoneBuff)":"https://www.youtube.com/TechnicalGuruji",
  "Shlok Srivastava":       "https://www.youtube.com/@TechBurner",
  "Jai Arora":              "https://www.youtube.com/@techielashorts",
  "Naman Deshmukh":         "https://www.youtube.com/@TechPlusGadgetsyt",
  "Manoj Saru":             "https://www.youtube.com/@TechnologyGyan",
  "Nagma Mirajkar":         "https://www.youtube.com/@nagmamirajkar",
  "Komal Pandey":           "https://www.youtube.com/channel/UCx2JNgWJPPTBODN-U56O-tg",
  "Kritika Khurana":        "https://www.youtube.com/@thatbohogirl",
  "Vikas Khanna":           "https://www.youtube.com/@vikaskhannagroup",
  "Shipra Khanna":          "https://www.youtube.com/@MasterChefShipraKhanna",
  "Ranveer Brar":           "https://www.youtube.com/@RanveerBrar",
  "Kunal Kapur":            "https://www.youtube.com/@ChefKunalKapur",
  "Hebbar's Kitchen":       "https://www.youtube.com/@hebbars.kitchen",
  "Shivesh Bhatia":         "https://www.youtube.com/@shivesh17",
  "Pankaj Bhadouria":       "https://www.youtube.com/@PankajBhadouria",
  "Techno Gamerz (Ujjwal Chaurasia)":"https://www.youtube.com/@technogamerz",
  "Total Gaming (Ajay)":    "https://www.youtube.com/@TotalGamingYT",
  "Dynamo Gaming (Aadi Sawant)":"https://www.youtube.com/@DynamoGaming",
  "Mortal (Naman Mathur)":  "https://www.youtube.com/@MortaL",
  "GamerFleet (Anshu Bisht)":"https://www.youtube.com/@GamerFleet",
  "Desi Gamers (Amit Sharma)":"https://www.youtube.com/@DesiGamersYT",
  "Simran Chopra":          "https://www.youtube.com/@simrunchopra",
  "Namrata Purohit":        "https://www.youtube.com/@NamrataPurohit",
  "Rohit Khatri":           "https://www.youtube.com/@rohitkhatri",
  "Yasmin Karachiwala":     "https://www.youtube.com/@YasminKarachiwala",
};

// ── Verified Instagram URLs ────────────────────────────────────────────────────
export const IG_VERIFIED = {
  "Shivam Malik":"https://www.instagram.com/shivammalik09/",
  "Abhishek Kar":"https://www.instagram.com/abhishekkarofficial/",
  "Sarthak Ahuja":"https://www.instagram.com/casarthakahuja/",
  "Sharan Hegde":"https://www.instagram.com/financewithsharan/",
  "Neha Nagar":"https://www.instagram.com/iamnehanagar/",
  "AISM India":"https://www.instagram.com/aismindia/",
  "Sakchi Jain":"https://www.instagram.com/ca.sakchijain/",
  "Groww.in":"https://www.instagram.com/groww_official/",
  "Ankur Warikoo":"https://www.instagram.com/ankurwarikoo/",
  "Businessman Hindi Mindset":"https://www.instagram.com/businessman_hindi_mindset/",
  "Gaurav Chaudhary (PhoneBuff)":"https://www.instagram.com/technicalguruji/",
  "Shlok Srivastava":"https://www.instagram.com/techburner/",
  "Jai Arora":"https://www.instagram.com/tech_iela/",
  "Naman Deshmukh":"https://www.instagram.com/techplusgadgets/",
  "Manoj Saru":"https://www.instagram.com/manajsaru/",
  "Nagma Mirajkar":"https://www.instagram.com/nagmamirajkar/",
  "Karron S Dhinggra":"https://www.instagram.com/theformaledit/",
  "Komal Pandey":"https://www.instagram.com/komalpandey/",
  "Kritika Khurana":"https://www.instagram.com/thatbohogirl/",
  "Ritik Mahajan":"https://www.instagram.com/ritikmahajan/",
  "Sakshi Shrivas":"https://www.instagram.com/sakshishrivas/",
  "Masoom Minawala":"https://www.instagram.com/masoomminawala/",
  "Sakshi Sindwani":"https://www.instagram.com/sakshisindwani/",
  "Pooja Dhingra":"https://www.instagram.com/poojadhingra/",
  "Vikas Khanna":"https://www.instagram.com/vikaskhannagroup/",
  "Shipra Khanna":"https://www.instagram.com/masterchefshiprakhanna/",
  "Ranveer Brar":"https://www.instagram.com/ranveer.brar/",
  "Kunal Kapur":"https://www.instagram.com/chefkunal/",
  "Hebbar's Kitchen":"https://www.instagram.com/hebbarskitchen/",
  "Shivesh Bhatia":"https://www.instagram.com/shivesh17/",
  "Eshaan Nagpal (Indian Bawarchi)":"https://www.instagram.com/indian_bawarchi/",
  "Pankaj Bhadouria":"https://www.instagram.com/masterchefpankajbhadouria/",
  "Amar Sirohi (Foodie Incarnate)":"https://www.instagram.com/foodie_incarnate/",
  "Techno Gamerz (Ujjwal Chaurasia)":"https://www.instagram.com/technogamerz/",
  "Total Gaming (Ajay)":"https://www.instagram.com/totalgaming_official/",
  "Dynamo Gaming (Aadi Sawant)":"https://www.instagram.com/dynamo__gaming/",
  "Mortal (Naman Mathur)":"https://www.instagram.com/ig_mortal/",
  "As Gaming (Sahil Rana)":"https://www.instagram.com/asgaming/",
  "GamerFleet (Anshu Bisht)":"https://www.instagram.com/gamerfleet/",
  "Kronten Gaming (Chetan Chandgude)":"https://www.instagram.com/krontengaming/",
  "Desi Gamers (Amit Sharma)":"https://www.instagram.com/desigamers/",
  "Two Side Gamers":"https://www.instagram.com/twosidegamers/",
  "Simran Chopra":"https://www.instagram.com/simrun.chopra/",
  "Pooja Makhija":"https://www.instagram.com/poojamakhija/",
  "Namrata Purohit":"https://www.instagram.com/namratapurohit/",
  "Luke Coutinho":"https://www.instagram.com/lukecoutinho/",
  "Rohit Khatri":"https://www.instagram.com/rohitkhatri/",
  "Varun Verma":"https://www.instagram.com/varunverma/",
  "Yasmin Karachiwala":"https://www.instagram.com/yasminkarachiwala/",
  "Nitesh Soni":"https://www.instagram.com/niteshsoniy/",
  "Soniya Singh Khatri":"https://www.instagram.com/fitgirl_08/",
};

// ── Domain avatar gradient stops ───────────────────────────────────────────────
export const DOMAIN_GRAD = {
  finance:  ['#00C48C','#00E8A8'],
  tech:     ['#2E6BFF','#6EA0FF'],
  fashion:  ['#FF3D71','#FF8AAB'],
  food:     ['#FF8A00','#FFB347'],
  gaming:   ['#A855F7','#C084FC'],
  fitness:  ['#00BBD6','#4DD9EE'],
  all:      ['#7C3AED','#A78BFA'],
};

// ── Domain metadata ────────────────────────────────────────────────────────────
export const DOMAIN_META = {
  all:     {label:"All",     var:"--c-all", title:"All Creators",           desc:"India's complete directory of top content creators across every domain."},
  finance: {label:"Finance", var:"--c-fin", title:"Finance & Investing",    desc:"India's top voices on personal finance, markets, budgeting and wealth creation."},
  tech:    {label:"Tech",    var:"--c-tech",title:"Tech & Gadgets",         desc:"India's most trusted tech reviewers — smartphones, AI tools, gadgets and more."},
  fashion: {label:"Fashion", var:"--c-mkt", title:"Fashion & Lifestyle",    desc:"India's leading fashion creators covering style, beauty, grooming and lifestyle."},
  food:    {label:"Food",    var:"--c-ops", title:"Food & Cooking",         desc:"India's top chefs and food creators — recipes, restaurant reviews and culinary stories."},
  gaming:  {label:"Gaming",  var:"--c-hr",  title:"Gaming & Esports",      desc:"India's biggest gaming creators — gameplay, esports, commentary and gaming culture."},
  fitness: {label:"Fitness", var:"--c-pm",  title:"Fitness & Wellness",    desc:"India's top fitness trainers and nutritionists — workouts, nutrition and holistic health."},
};

export const ORDER = ['all','finance','tech','fashion','food','gaming','fitness'];

// ── Animated domain icons (SVG) ────────────────────────────────────────────────
export const ICONS = {
  all:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><g data-orbit><circle cx="24" cy="24" r="17" stroke-dasharray="4 6"/></g><circle cx="24" cy="24" r="6" fill="currentColor" stroke="none" data-pulse/><circle cx="24" cy="7" r="3" fill="currentColor" stroke="none"/><circle cx="41" cy="24" r="3" fill="currentColor" stroke="none"/><circle cx="24" cy="41" r="3" fill="currentColor" stroke="none"/><circle cx="7" cy="24" r="3" fill="currentColor" stroke="none"/></svg>',
  finance:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><rect data-grow x="9" y="26" width="6" height="13" rx="2" fill="currentColor" stroke="none"/><rect data-grow x="21" y="20" width="6" height="19" rx="2" fill="currentColor" fill-opacity=".55" stroke="none"/><rect data-grow x="33" y="13" width="6" height="26" rx="2" fill="currentColor" stroke="none"/><path d="M9 16l9-6 7 4 14-9" data-draw/><path d="M40 5v6h-6"/></svg>',
  tech:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><rect x="14" y="14" width="20" height="20" rx="4" fill="currentColor" fill-opacity=".12"/><g data-spin><rect x="20" y="20" width="8" height="8" rx="2" fill="currentColor" stroke="none"/></g><path d="M19 14V8M29 14V8M19 40v-6M29 40v-6M14 19H8M14 29H8M40 19h-6M40 29h-6"/></svg>',
  fashion:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M16 6l-6 10h8v2c0 3 2 5 6 5s6-2 6-5v-2h8L32 6" fill="currentColor" fill-opacity=".13"/><path data-bounce d="M24 23v16"/><path d="M18 39h12"/><circle cx="24" cy="10" r="3" fill="currentColor" stroke="none" data-pulse/></svg>',
  food:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M8 8v10c0 5 4 8 8 8s8-3 8-8V8" fill="currentColor" fill-opacity=".12"/><line x1="12" y1="8" x2="12" y2="18"/><line x1="16" y1="8" x2="16" y2="18"/><line x1="20" y1="8" x2="20" y2="18"/><path data-draw d="M32 8c0 0 8 4 8 14"/><path d="M36 22v18"/></svg>',
  gaming:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="15" width="36" height="22" rx="8" fill="currentColor" fill-opacity=".12"/><path data-draw d="M18 26h4m-2-2v4"/><circle cx="30" cy="24" r="1.5" fill="currentColor" stroke="none" data-pulse/><circle cx="34" cy="27" r="1.5" fill="currentColor" stroke="none"/></svg>',
  fitness:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="20" width="5" height="8" rx="2" fill="currentColor" stroke="none"/><rect x="40" y="20" width="5" height="8" rx="2" fill="currentColor" stroke="none"/><rect x="8" y="22" width="7" height="4" rx="2" fill="currentColor" fill-opacity=".5" stroke="none"/><rect x="33" y="22" width="7" height="4" rx="2" fill="currentColor" fill-opacity=".5" stroke="none"/><rect x="15" y="17" width="18" height="14" rx="3" fill="currentColor" fill-opacity=".15"/><g data-bounce><rect x="17" y="19" width="14" height="10" rx="2" fill="currentColor" stroke="none"/></g></svg>',
};
